# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TyreService' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TyreService

  pod 'Alamofire', '~> 5.4'

  target 'TyreServiceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TyreServiceUITests' do
    # Pods for testing
  end

end
